// Generated by CoffeeScript 1.6.2
(function() {
  toast('src', {
    vendors: ['vendors/dat.gui.min.js', 'vendors/physics.min.js', 'vendors/sketch.js', 'vendors/CSSMatrix.js', 'vendors/Tween.js', 'vendors/Timeline.js', 'vendors/TweenObject.js', 'vendors/svg.min.js', 'vendors/EventEmitter-4.0.3.min.js'],
    bare: true,
    packaging: false,
    minify: true,
    httpfolder: 'js',
    release: 'www/js/dhaakon-portfolio.js',
    debug: 'www/js/dhaakon-portfolio-debug.js'
  });

}).call(this);
