// Generated by CoffeeScript 1.6.2
(function() {
  toast('src', {
    exclude: ['src/site/'],
    bare: false,
    packaging: false,
    expose: '',
    minify: false,
    httpfolder: '',
    release: 'app/app.js',
    debug: 'app/app-debug.js'
  });

}).call(this);
